### ISSUE TITLE
Neruina Fabric 2.2.6 for 1.19.2 Crashes on world load

### ISSUE THREAD

**Issue by SlayerTheChikken** [Benjamin-Norton/Neruina#126]
[crash-2024-12-15_11.07.35-server.txt](https://github.com/user-attachments/files/18141166/crash-2024-12-15_11.07.35-server.txt)

**Comment by Bawnorton** [comment]
One of your other mods bundles an older version of gson, which breaks neruina. I'll look into a workaround

**Comment by Bawnorton** [comment]
Fixed in 2.2.7

**Comment by SlayerTheChikken** [comment]
Yay thank u

Sent from Proton Mail Android

-------- Original Message --------

**Comment by SlayerTheChikken** [comment]
@Bawnorton Unfortunately this issue still happens, is there any way for me to fix this for just my modpack? I'm not sure which mod is shipping the older gson

**Comment by Bawnorton** [comment]
Can you send the new log, thanks

**Comment by SlayerTheChikken** [comment]
[crash-2025-01-10_18.08.38-server.txt](https://github.com/user-attachments/files/18384279/crash-2025-01-10_18.08.38-server.txt)
[crash-2025-01-10_18.10.13-server.txt](https://github.com/user-attachments/files/18384280/crash-2025-01-10_18.10.13-server.txt)

**Comment by SlayerTheChikken** [comment]
Sorry for taking so long i forgot to give the new crash log ;-;

**Comment by Bawnorton** [comment]
Try 2.2.8
